# MODEL INFARANCE P1G2

### NAMA : IQBAL JANITRA

### BATCH : 003

# IMPORT LIBRARIES

In [133]:
import pandas as pd
import numpy as np
import joblib

# LOAD DATA

In [114]:
with open('model_log_reg.pkl', 'rb') as file_1:
  model_log_reg= joblib.load(file_1)

with open('model_scaler.pkl', 'rb') as file_2:
  model_scaler=joblib.load(file_2)

with open('model_encoder.pkl', 'rb') as file_3:
  model_encoder= joblib.load(file_3)

with open('list_num_cols.txt', 'rb') as file_4:
  num_cols= joblib.load(file_4)

with open('list_cat_cols.txt', 'rb') as file_5:
  cat_cols= joblib.load(file_5)

### MAKING RANDOM VALUE BASED ON FEATURES

In [115]:
random = np.random.default_rng(seed=2895)
capital_gain = random.integers(0, 99999, size=30)
education_num = random.uniform(1, 16, size=30)
hours_per_week = random.integers(0, 99, size=30)
occupation = random.choice([ ' Craft-repair', ' Transport-moving', ' Sales', ' Adm-clerical',
                             ' Other-service', ' Farming-fishing', ' Prof-specialty',
                             ' Exec-managerial', ' Protective-serv', ' Handlers-cleaners',
                             ' Priv-house-serv', ' Machine-op-inspct', ' Tech-support'], size=30)
sex = random.choice([' Female',' Male'], size=30)
data_inf = pd.DataFrame({'capital_gain' : capital_gain, 'education_num' : education_num, 'hours_per_week' : hours_per_week, 'sex' :sex, 'occupation':occupation})
data_inf

    capital_gain  education_num  hours_per_week      sex          occupation
0           4465       1.567401              70     Male        Tech-support
1          99217       8.527770              61     Male     Priv-house-serv
2          50455      12.568554              85   Female        Adm-clerical
3           7268       5.832824              55     Male               Sales
4          34377       3.748387              48   Female        Tech-support
5          67580      12.353544              98     Male     Protective-serv
6          11580       5.449391              31   Female   Handlers-cleaners
7          74164      11.726187              43   Female        Tech-support
8          53415       4.099595              22     Male    Transport-moving
9          82332      15.921822              13     Male   Machine-op-inspct
10         78065      14.577626              56     Male   Machine-op-inspct
11         98112       9.298705              98   Female        Craft-repair
12         18684       7.074334               5     Male     Farming-fishing
13         41731       3.365113              97     Male        Tech-support
14         79939       6.518888              64     Male    Transport-moving
15         57842      12.859712              95     Male       Other-service
16         68053      15.804688              52     Male      Prof-specialty
17         32739       4.321618              68     Male        Adm-clerical
18         83185      12.546851              35   Female   Machine-op-inspct
19         85157       6.549868              85   Female     Protective-serv
20         73051       4.424113              78   Female      Prof-specialty
21         44437       6.532371              65     Male        Adm-clerical
22         66560      10.282577              44     Male   Handlers-cleaners
23         70968       4.960512              35   Female        Tech-support
24         61916       2.198235              81     Male        Craft-repair
25         11010      15.921134               8     Male     Exec-managerial
26         73170      10.631419              66   Female     Protective-serv
27         70984       5.915938              75   Female     Priv-house-serv
28         16160       2.147935              23     Male        Tech-support
29         48319       5.773004              96   Female   Machine-op-inspct

# MODEL

In [129]:
data_inf_num = data_inf[num_cols]
data_inf_cat = data_inf[cat_cols]

In [130]:
data_inf_num_scaled = model_scaler.transform(data_inf_num)
data_inf_cat_encoded = model_encoder.transform(data_inf_cat)

In [131]:
data_inf_final = np.concatenate([data_inf_num_scaled, data_inf_cat_encoded], axis=1)

### Making prediction INCOME BRACKET

In [132]:
y_pred_inf = model_log_reg.predict(data_inf_final)
y_pred_inf

array([' <=50K', ' >50K', ' >50K', ' <=50K', ' <=50K', ' >50K', ' <=50K',
       ' >50K', ' <=50K', ' >50K', ' >50K', ' >50K', ' <=50K', ' >50K',
       ' >50K', ' >50K', ' >50K', ' >50K', ' >50K', ' >50K', ' >50K',
       ' >50K', ' >50K', ' <=50K', ' >50K', ' <=50K', ' >50K', ' >50K',
       ' <=50K', ' >50K'], dtype=object)

# CONCLUSION

After we choose the features and make model of it we just finish make `Model Inferance` use `LinearReggresion` method, this method have the best precision and f1 for this time, and for `model inferance` we can do prediction how much income_bracket based on the features we choosed.